plugins {
  id 'java'
}

sourceSets {
  main.java {
    srcDir '.'
    include 'perf', 'knn'
  }
  test.java {
    srcDir '../test'
    include 'perf/LocalTaskSourceWorkloadTest.java'
  }
}

tasks.register('testExactWorkloadPhases', JavaExec) {
  dependsOn testClasses
  classpath = sourceSets.test.runtimeClasspath
  mainClass = 'perf.LocalTaskSourceWorkloadTest'
}

def luceneDir = (String) findProperty("external.lucene.repo") + '/lucene'
def luceneVersion = (String) findProperty("lucene.version")

dependencies {
  implementation fileTree(dir: luceneDir, include: "**/*$luceneVersion-SNAPSHOT.jar")
}
